
model:
  kwargs:
    type: MMBSN
    pd_a: 5
    pd_b: 2
    pd_pad: 2
    R3: True
    R3_T: 8
    R3_p: 0.16
    in_ch: 3
    bsn_base_ch: 128
    bsn_num_module: 9
    DCL1_num: 2
    DCL2_num: 7
    mask_type: 'o_a45' #e.g.: r/c/sz/fsz/a45/a135/cha/fcha
    
model_input: [noisy] # e.g.) real_noisy, syn_noisy, clean

trainer: Trainer

training:
  dataset: prep_SIDD

  dataset_args:
    crop_size: [120, 120]
    aug: ['hflip', 'rot']
    n_repeat: 1
  
  batch_size: 8

  max_epoch: 30
  
  init_lr: 1e-4
  scheduler:
    type: step
    step:
      step_size: 8
      gamma: 0.1
  loss: 1*self_L1
  tmp_info: []
  optimizer:
    type: Adam
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 200

validation:
  dataset: SIDD_val

  dataset_args:
    crop_size: None # [64, 64]
    n_data: 64

  add_con: 0.5
  floor: True

  val: True
  save_image: True
  
  start_epoch: 1
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 10

test:
  dataset: SIDD_benchmark

  dataset_args:
    crop_size: None # [64, 64]

  add_con: 0.5
  floor: True

  save_image: True
